### ISSUE TITLE
We need a push skipping strategy in seta

### ISSUE THREAD

**Issue by MikeLing** [mozilla/ouija#117]
we need a new push skipping strategy in seta, which is make seta return low_value_jobs and return full job list every 5 push and 90 minutes. Does it sounds good to you? @jmaher

**Comment by jmaher** [comment]
this sounds great, probably a simple database table to count.  A more complete way would be a table of branch/revisions that would work in case the decision task was rerun (which happens often enough) and would give us options for multiple priorities.

Another option is a list of jobtypes:branch, with a count of requests.  If we get a series of decision task retriggers then this will be skewed.

The simplest method would be anytime the endpoint is called for a branch, increment a counter/timestamp, and when we hit our limit 5 requests or 90 minutes, then we return all high+low value jobs.  If we did this, I would like to experiment with a more complete solution- this simple solution would be faster to implement and might shed light on other quirks.

**Comment by MikeLing** [comment]
Yeah, it makes sense to me! Do you think pushlog_id is a good identifier for a decision task? or head_rev?

**Comment by jmaher** [comment]
I think either will work and I believe we can get both pieces of information from the decision task.  head_rev might be easier to match up to treeherder views, and to ingested data if we are trying to figure out what went wrong.  it is not as easy to read as pushlog_id, but seems like it would be slightly easier to work with.

**Comment by MikeLing** [comment]
@jmaher , things seems become pretty complex after we want to calculate pushes for each branch.
I think we should exact data set from TaskRequest table and sort them by each branch. Furthermore, we should sort those data set by timestamp. So we should exact last 4 pushes for that branch and see if the priorities are all **1**(which means low jobs returned) If last 4 pushes for that branch are all **1**, we return all jobs for that push and store it in table with priority **0**.

But the problem is, we will query and sort all data sets each time when a new request comes. Maybe it's a little expensive and time consuming for a push request? What should I do to make this whole process as fast as possible? Thank you!

**Comment by jmaher** [comment]
this is a great point and something I am not sure about.  In a perfect world we would have every possible job (~1500) for each branch (~10) and have a priority and history for each.  So that would be ~15000 rows in a table with:
job, branch, last_request_date, number_requests, max_requests

so every query would update the last_request_date, and increment the number_requests.  If number_requests >= max_requests, it is reset to 0.

But that is expensive- we would have to make 1500+ requests for each decision task, or pass around that much data.  So I do not think that is useful.  We could make a request generic "new request, branch, revision" coming from the decision task, then we can get the date of the request and know the branch.

I don't think we can realistically be fast about assigning specific skip counts to every single job.  We will have the same SETA data for each of the integration branches- possibly some custom configs for mozilla-central, mozilla-aurora, and try.  Instead of doing a custom query for each request that comes in, we can cache the results of a query (since these are only updated when failures.py is run).  Given multiple priorities we then only have 1 set of data for each priority.  So for high/low, we have 1 set of data (the high value jobs), whereas the low value jobs is everything!

In summary, we get a request and we need to keep track of the branch, date, number_of_requests.  I see this as a single insert into a table, and a single query from the table.  Possibly a second query if we need to get the list of jobs at priority X.

# assuming a 5 priority system
jobs_to_run = {'1': [], '2': [], '3': [], '4': [], '5': []}
so request comes in: _branch, _revision, _push_id
we store the results: update skipcount set branch=_branch, date=current_date, numrequests=(numrequests +1)
_priority = query(select numrequests from skipcount where branch=_branch)
if _priority == 0:
    update skipcount set numrequests=0 where branch=_branch
    # compare dates to see if we hit 12 hours
    if currentdate > previous_update_date + 12*hours:
        # TODO: this will slow us down
        previous_update_date = currentdate
        for p in range(1,5):
            jobs_to_run[p] = query(select jobnames from seta_jobs where priority=p)
    return [] # to run all the tests
else:
    return jobs_to_run[_priority]

------------

^ the above code will assume a simple counter system for each branch, possibly it needs more refinement to be complete.

**Comment by MikeLing** [comment]
Hmm, I think the really consuming thing is how to deal with the retrigger task. How to keep the job list we give to that task is exactly same with the last time we give.

**Comment by jmaher** [comment]
the job list will be stored in server.py scope as an in memory variable, it will get updated with the latest bits frequently

**Comment by jmaher** [comment]
we have this implemented!
